services:

  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    # restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    name: "smog-data"
    external: true
  